import io
import os
from datetime import datetime
from typing import Optional
import pandas as pd

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, HRFlowable, KeepTogether
)
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to calculate total page count dynamically
    and render professional running footers with page numbers.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))

        # Footer divider line
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(36, 40, 576, 40)

        # Footer Left & Right text
        footer_text = "Generated by Work Order Management System"
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawString(36, 26, footer_text)
        self.drawRightString(576, 26, page_str)

        self.restoreState()


def create_workorder_pdf(
    df: pd.DataFrame,
    company_name: str = "AI4I Industrial Solutions",
    generated_by: str = "Admin",
    logo_path: Optional[str] = None
) -> bytes:
    """
    Generates a professional Work Order PDF report using ReportLab.

    Parameters:
        df (pd.DataFrame): Work Order records to include in report.
        company_name (str): Name of the organization.
        generated_by (str): Name/Role of the person generating report.
        logo_path (str, optional): Path to company logo image file.

    Returns:
        bytes: Raw binary bytes of generated PDF document.
    """
    buffer = io.BytesIO()

    # Document setup: Letter size with 0.5 inch (36 pt) side margins
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=54
    )

    story = []

    # Sample stylesheet & custom styles
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#0F172A'),
        spaceAfter=4
    )

    company_style = ParagraphStyle(
        'CompanyTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=14,
        textColor=colors.HexColor('#1E3A8A')
    )

    meta_label_style = ParagraphStyle(
        'MetaLabel',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor('#475569')
    )

    meta_val_style = ParagraphStyle(
        'MetaValue',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor('#0F172A')
    )

    section_heading_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=15,
        textColor=colors.HexColor('#1E3A8A'),
        spaceBefore=10,
        spaceAfter=6
    )

    tbl_header_style = ParagraphStyle(
        'TblHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=11,
        textColor=colors.white,
        alignment=1  # Centered
    )

    tbl_cell_style = ParagraphStyle(
        'TblCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8,
        leading=10,
        textColor=colors.HexColor('#1E293B')
    )

    tbl_cell_center = ParagraphStyle(
        'TblCellCenter',
        parent=tbl_cell_style,
        alignment=1  # Centered
    )

    kpi_val_style = ParagraphStyle(
        'KPIVal',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=16,
        alignment=1,
        textColor=colors.HexColor('#0F172A')
    )

    kpi_lbl_style = ParagraphStyle(
        'KPILbl',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=7.5,
        leading=9,
        alignment=1,
        textColor=colors.HexColor('#475569')
    )

    # -------------------------------------------------------------
    # 1. Header Section (Logo, Company Name, Title, Generation Metadata)
    # -------------------------------------------------------------
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    header_left_elements = []
    if logo_path and os.path.exists(logo_path):
        try:
            img = Image(logo_path, width=1.2 * 72, height=0.5 * 72)
            header_left_elements.append(img)
        except Exception:
            pass

    header_left_elements.append(Paragraph(company_name, company_style))
    header_left_elements.append(Paragraph("Work Order Report", title_style))

    # Meta table right column
    meta_data = [
        [Paragraph("Report Date:", meta_label_style), Paragraph(now_str, meta_val_style)],
        [Paragraph("Generated By:", meta_label_style), Paragraph(generated_by, meta_val_style)]
    ]
    meta_table = Table(meta_data, colWidths=[70, 110])
    meta_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (0, 0), (-1, -1), 'RIGHT'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 1),
        ('TOPPADDING', (0, 0), (-1, -1), 1),
    ]))

    header_table_data = [[header_left_elements, meta_table]]
    header_table = Table(header_table_data, colWidths=[360, 180])
    header_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (1, 0), (1, 0), 'RIGHT'),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0),
        ('TOPPADDING', (0, 0), (-1, -1), 0),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))

    story.append(header_table)
    story.append(Spacer(1, 4))

    # Horizontal divider line below header
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#1E3A8A'), spaceBefore=2, spaceAfter=8))

    # -------------------------------------------------------------
    # 2. Executive Summary Cards (KPI Table)
    # -------------------------------------------------------------
    total_wos = len(df)
    if total_wos > 0 and 'status' in df.columns:
        status_series = df['status'].astype(str).str.strip().str.lower()
        open_wos = len(df[status_series.isin(['open', 'pending'])])
        in_progress_wos = len(df[status_series == 'in progress'])
        completed_wos = len(df[status_series == 'completed'])
    else:
        open_wos = 0
        in_progress_wos = 0
        completed_wos = 0

    if total_wos > 0 and 'priority' in df.columns:
        prio_series = df['priority'].astype(str).str.strip().str.lower()
        high_prio_wos = len(df[prio_series.isin(['high', 'critical'])])
    else:
        high_prio_wos = 0

    summary_card_data = [
        [
            Paragraph("TOTAL WOs", kpi_lbl_style),
            Paragraph("OPEN WOs", kpi_lbl_style),
            Paragraph("IN PROGRESS", kpi_lbl_style),
            Paragraph("COMPLETED", kpi_lbl_style),
            Paragraph("HIGH PRIORITY", kpi_lbl_style)
        ],
        [
            Paragraph(str(total_wos), kpi_val_style),
            Paragraph(str(open_wos), kpi_val_style),
            Paragraph(str(in_progress_wos), kpi_val_style),
            Paragraph(str(completed_wos), kpi_val_style),
            Paragraph(str(high_prio_wos), kpi_val_style)
        ]
    ]

    summary_table = Table(summary_card_data, colWidths=[108, 108, 108, 108, 108])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, 0), 4),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 2),
        ('TOPPADDING', (0, 1), (-1, 1), 2),
        ('BOTTOMPADDING', (0, 1), (-1, 1), 5),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER')
    ]))

    story.append(Paragraph("Executive Summary", section_heading_style))
    story.append(summary_table)
    story.append(Spacer(1, 10))

    # -------------------------------------------------------------
    # 3. Work Orders Main Data Table
    # -------------------------------------------------------------
    story.append(Paragraph("Work Order Details", section_heading_style))

    # Headers required: Work Order ID, Title, Description, Assigned To, Priority, Status, Created Date, Due Date
    table_headers = [
        Paragraph("Work Order ID", tbl_header_style),
        Paragraph("Title", tbl_header_style),
        Paragraph("Description", tbl_header_style),
        Paragraph("Assigned To", tbl_header_style),
        Paragraph("Priority", tbl_header_style),
        Paragraph("Status", tbl_header_style),
        Paragraph("Created Date", tbl_header_style),
        Paragraph("Due Date", tbl_header_style)
    ]

    table_rows = [table_headers]

    if not df.empty:
        for idx, row in df.iterrows():
            wo_id = str(row.get('work_order_id', f"WO-{idx+1:03d}"))
            
            # Map Title cleanly from DataFrame columns
            if 'title' in row and pd.notnull(row['title']):
                title = str(row['title'])
            elif 'maintenance_action' in row and pd.notnull(row['maintenance_action']):
                title = str(row['maintenance_action'])
            elif 'machine_id' in row and pd.notnull(row['machine_id']):
                title = f"Machine {row['machine_id']}"
            else:
                title = "N/A"

            # Map Description cleanly
            if 'description' in row and pd.notnull(row['description']):
                desc = str(row['description'])
            elif 'ai_summary' in row and pd.notnull(row['ai_summary']):
                desc = str(row['ai_summary'])
            elif 'failure_type' in row and pd.notnull(row['failure_type']):
                desc = f"Failure: {row['failure_type']}"
            else:
                desc = "No details provided."

            assigned_to = str(row.get('assigned_to', 'Unassigned'))
            priority = str(row.get('priority', 'Low'))
            status = str(row.get('status', 'Pending'))
            
            # Created Date formatting
            created_raw = row.get('created_date', row.get('created_at', 'N/A'))
            if pd.notnull(created_raw):
                created_str = str(created_raw).split(' ')[0]
            else:
                created_str = "N/A"

            # Due Date formatting
            due_raw = row.get('due_date', 'N/A')
            if pd.notnull(due_raw):
                due_str = str(due_raw).split(' ')[0]
            else:
                due_str = "N/A"

            table_rows.append([
                Paragraph(wo_id, tbl_cell_style),
                Paragraph(title, tbl_cell_style),
                Paragraph(desc, tbl_cell_style),
                Paragraph(assigned_to, tbl_cell_style),
                Paragraph(priority, tbl_cell_center),
                Paragraph(status, tbl_cell_center),
                Paragraph(created_str, tbl_cell_center),
                Paragraph(due_str, tbl_cell_center)
            ])
    else:
        # Fallback empty row if no records
        table_rows.append([
            Paragraph("N/A", tbl_cell_style),
            Paragraph("No work orders available", tbl_cell_style),
            Paragraph("-", tbl_cell_style),
            Paragraph("-", tbl_cell_style),
            Paragraph("-", tbl_cell_center),
            Paragraph("-", tbl_cell_center),
            Paragraph("-", tbl_cell_center),
            Paragraph("-", tbl_cell_center)
        ])

    # Printable width: 540 pt
    # Col widths sum: 75 + 85 + 115 + 75 + 48 + 52 + 45 + 45 = 540
    col_widths = [75, 85, 115, 75, 48, 52, 45, 45]

    wo_table = Table(table_rows, colWidths=col_widths, repeatRows=1)

    # Style table with primary blue header, white header text, alternating row colors, grid borders
    t_style = [
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E3A8A')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 5),
        ('TOPPADDING', (0, 0), (-1, 0), 5),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
    ]

    # Alternating row background colors (#FFFFFF & #F8FAFC)
    for i in range(1, len(table_rows)):
        bg_color = colors.HexColor('#F8FAFC') if i % 2 == 0 else colors.white
        t_style.append(('BACKGROUND', (0, i), (-1, i), bg_color))
        t_style.append(('TOPPADDING', (0, i), (-1, i), 4))
        t_style.append(('BOTTOMPADDING', (0, i), (-1, i), 4))

    wo_table.setStyle(TableStyle(t_style))
    story.append(wo_table)

    # Build document using NumberedCanvas
    doc.build(story, canvasmaker=NumberedCanvas)

    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes


def create_machine_pdf(
    machine_info: dict,
    ai_summary: str = "",
    company_name: str = "AI4I Industrial Solutions",
    generated_by: str = "Admin"
) -> bytes:
    """
    Generates an optimized, single machine telemetry and AI diagnostic PDF report.
    """
    import re
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=54
    )

    story = []
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=18,
        leading=22,
        textColor=colors.HexColor('#0F172A'),
        spaceAfter=4
    )

    company_style = ParagraphStyle(
        'CompanyTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=11,
        leading=13,
        textColor=colors.HexColor('#1E3A8A')
    )

    meta_label_style = ParagraphStyle(
        'MetaLabel',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor('#475569')
    )

    meta_val_style = ParagraphStyle(
        'MetaValue',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor('#0F172A')
    )

    section_heading_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=11,
        leading=14,
        textColor=colors.HexColor('#1E3A8A'),
        spaceBefore=8,
        spaceAfter=4
    )

    body_style = ParagraphStyle(
        'BodyTextCustom',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor('#1E293B'),
        spaceAfter=3
    )

    tbl_header_style = ParagraphStyle(
        'TblHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=11,
        textColor=colors.white,
        alignment=0
    )

    tbl_cell_style = ParagraphStyle(
        'TblCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8,
        leading=10,
        textColor=colors.HexColor('#1E293B')
    )

    # 1. Header Block
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    p_id = str(machine_info.get('product_id', 'N/A'))
    m_type = str(machine_info.get('type', 'N/A'))
    failures = str(machine_info.get('failures', 'None'))

    header_left = [
        Paragraph(company_name, company_style),
        Paragraph(f"Machine Diagnostic Report — {p_id}", title_style)
    ]

    meta_data = [
        [Paragraph("Report Date:", meta_label_style), Paragraph(now_str, meta_val_style)],
        [Paragraph("Generated By:", meta_label_style), Paragraph(generated_by, meta_val_style)],
        [Paragraph("Machine ID:", meta_label_style), Paragraph(p_id, meta_val_style)]
    ]
    meta_table = Table(meta_data, colWidths=[70, 110])
    meta_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (0, 0), (-1, -1), 'RIGHT'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 1),
        ('TOPPADDING', (0, 0), (-1, -1), 1),
    ]))

    header_table = Table([[header_left, meta_table]], colWidths=[360, 180])
    header_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (1, 0), (1, 0), 'RIGHT'),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0),
        ('TOPPADDING', (0, 0), (-1, -1), 0),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))

    story.append(header_table)
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#1E3A8A'), spaceBefore=2, spaceAfter=6))

    # 2. Equipment Overview & Health Status Table
    has_failure = failures != 'None' and failures != ''
    status_label = "CRITICAL / FAILURE PREDICTED" if has_failure else "OPERATIONAL / HEALTHY"
    status_color = colors.HexColor('#DC2626') if has_failure else colors.HexColor('#16A34A')

    status_p = Paragraph(f"<b><font color='white'>{status_label}</font></b>", ParagraphStyle('StatP', parent=styles['Normal'], alignment=1, fontSize=8.5, leading=10))

    specs_table_data = [
        [
            Paragraph("Product ID", tbl_header_style),
            Paragraph("Machine Type", tbl_header_style),
            Paragraph("Detected Failures", tbl_header_style),
            Paragraph("Health Status", tbl_header_style)
        ],
        [
            Paragraph(p_id, tbl_cell_style),
            Paragraph(f"{m_type}-Series Equipment", tbl_cell_style),
            Paragraph(failures, tbl_cell_style),
            status_p
        ]
    ]

    specs_table = Table(specs_table_data, colWidths=[110, 130, 150, 150])
    specs_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E3A8A')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('BACKGROUND', (3, 1), (3, 1), status_color),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))

    story.append(Paragraph("1. Machine Identification & Health Overview", section_heading_style))
    story.append(specs_table)
    story.append(Spacer(1, 6))

    # 3. Live Sensor Telemetry Table
    sensor_rows = [
        [Paragraph("Telemetry Metric", tbl_header_style), Paragraph("Current Value", tbl_header_style), Paragraph("Operational Unit", tbl_header_style), Paragraph("Baseline Norm", tbl_header_style)],
        [Paragraph("Air Temperature", tbl_cell_style), Paragraph(str(machine_info.get('air_temp', 'N/A')), tbl_cell_style), Paragraph("Kelvin (K)", tbl_cell_style), Paragraph("295.0 - 304.5 K", tbl_cell_style)],
        [Paragraph("Process Temperature", tbl_cell_style), Paragraph(str(machine_info.get('process_temp', 'N/A')), tbl_cell_style), Paragraph("Kelvin (K)", tbl_cell_style), Paragraph("305.0 - 313.8 K", tbl_cell_style)],
        [Paragraph("Rotational Speed", tbl_cell_style), Paragraph(str(machine_info.get('rot_speed', 'N/A')), tbl_cell_style), Paragraph("RPM", tbl_cell_style), Paragraph("1168 - 2886 RPM", tbl_cell_style)],
        [Paragraph("Torque", tbl_cell_style), Paragraph(str(machine_info.get('torque', 'N/A')), tbl_cell_style), Paragraph("Newton-meters (Nm)", tbl_cell_style), Paragraph("3.8 - 76.6 Nm", tbl_cell_style)],
        [Paragraph("Tool Wear", tbl_cell_style), Paragraph(str(machine_info.get('tool_wear', 'N/A')), tbl_cell_style), Paragraph("Minutes (min)", tbl_cell_style), Paragraph("Max Limit: 200 min", tbl_cell_style)],
    ]

    sensor_table = Table(sensor_rows, colWidths=[150, 110, 130, 150])
    sensor_style = [
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E3A8A')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
    ]
    for i in range(1, len(sensor_rows)):
        bg = colors.HexColor('#F8FAFC') if i % 2 == 0 else colors.white
        sensor_style.append(('BACKGROUND', (0, i), (-1, i), bg))
        sensor_style.append(('TOPPADDING', (0, i), (-1, i), 3))
        sensor_style.append(('BOTTOMPADDING', (0, i), (-1, i), 3))

    sensor_table.setStyle(TableStyle(sensor_style))
    story.append(Paragraph("2. Real-Time Telemetry Sensor Readings", section_heading_style))
    story.append(sensor_table)
    story.append(Spacer(1, 6))

    # 4. AI Summary & Recommendations
    story.append(Paragraph("3. AI Maintenance Summary & Recommendations", section_heading_style))

    if ai_summary and len(ai_summary.strip()) > 0:
        lines = ai_summary.strip().split("\n")
        section_titles = [
            "MACHINE DIAGNOSTIC REPORT", "Machine Condition:", "Detected Issues:",
            "Root Cause Analysis:", "Maintenance Priority:", "Recommended Actions:",
            "Preventive Maintenance:", "Technician Note:", "Final Assessment:"
        ]
        for line in lines:
            line_str = line.strip()
            if not line_str:
                continue

            if line_str in section_titles or line_str.rstrip(':') in [s.rstrip(':') for s in section_titles]:
                story.append(Paragraph(f"<b>{line_str}</b>", section_heading_style))
            elif line_str.startswith("###") or line_str.startswith("##"):
                clean_heading = line_str.replace("#", "").strip()
                story.append(Paragraph(clean_heading, section_heading_style))
            elif line_str.startswith("- ") or line_str.startswith("• "):
                clean_bullet = line_str[2:].strip()
                clean_bullet = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', clean_bullet)
                clean_bullet = re.sub(r'`(.*?)`', r'<b>\1</b>', clean_bullet)
                story.append(Paragraph(f"• {clean_bullet}", body_style))
            elif re.match(r'^\d+\.\s+', line_str):
                clean_num = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line_str)
                clean_num = re.sub(r'`(.*?)`', r'<b>\1</b>', clean_num)
                story.append(Paragraph(clean_num, body_style))
            else:
                clean_text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line_str)
                clean_text = re.sub(r'`(.*?)`', r'<b>\1</b>', clean_text)
                story.append(Paragraph(clean_text, body_style))
    else:
        story.append(Paragraph("AI diagnostic summary unavailable for this equipment record.", body_style))

    doc.build(story, canvasmaker=NumberedCanvas)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes

